### ISSUE TITLE
[PE-D][Tester E] Broken hyperlink in assign command documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-2/tp#201]
The hyperlink to the appendix does not work when clicked.

![SCR-20231103-oukw.png](https://raw.githubusercontent.com/xenosf/ped/main/files/5e8b31b2-b66f-495d-bf67-6f5e041774c6.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: xenosf/ped#7

**Comment by thienmy0** [comment]
Completed in #243
