### ISSUE TITLE
[PE-D][Tester A] UG mentions additional prefixes for record that have not been defined.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-2/tp#209]
![Screenshot 2023-11-03 at 5.00.30 PM.png](https://raw.githubusercontent.com/MadLamprey/ped/main/files/5545f231-a7af-4a05-9ab0-895b18dea3cf.png)

The command has been directly taken from the UG [example for `record` command].

The prefixes `a/`, `t/`, `r/` have not been specified and appear as it is when the patient is viewed.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: MadLamprey/ped#8

**Comment by thienmy0** [comment]
Completed in #248
